---
# File: site.yml - Hubot playbook for Vagrant based instance

- name: Hubot activate!
  hosts: hubot
  sudo: True
  gather_facts: False
  roles:
  - { role: brianshumate.hubot, hubot_identity: hubot }
