---
# File handlers/main.yml Handlers for Hubot role

- name: enable hubot
  sudo: True
  service: name=hubot enabled=true

- name: restart hubot
  sudo: True
  service: name=hubot state=restarted

- name: start hubot
  sudo: True
  service: name=hubot state=started

- name: stop hubot
  sudo: True
  service: name=hubot state=stopped
